name: Deploy to AWS

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: plantasia
  EKS_CLUSTER: prod-plantasia
  EKS_ROLE_ARN: arn:aws:iam::476114158430:role/eks-cluster-access-role

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ env.EKS_ROLE_ARN }}
        role-duration-seconds: 1200

    - name: Configure kubectl
      run: |
        aws eks update-kubeconfig \
          --name ${{ env.EKS_CLUSTER }} \
          --region ${{ env.AWS_REGION }}