name: Deploy to AWS

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: plantasia
  EKS_CLUSTER: prod-plantasia
  EKS_ROLE_ARN: arn:aws:iam::476114158430:role/eks-cluster-access-role

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Check Identity
      run: |
        aws sts get-caller-identity

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: v${{ github.sha }}
      run: |
        # Build with platform specified
        docker build --platform linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Configure kubectl
      run: |
        aws eks update-kubeconfig \
          --name ${{ env.EKS_CLUSTER }} \
          --region ${{ env.AWS_REGION }}
        
        # Test connection
        kubectl get nodes

    - name: Deploy to EKS
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: v${{ github.sha }}
      run: |
        # Update deployment image
        kubectl set image deployment/plantasia plantasia=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
        # Check node status
        echo "Checking node status..."
        kubectl get nodes
        
        # Force rollout if needed
        echo "Forcing rollout restart..."
        kubectl rollout restart deployment/plantasia
        
        # Wait for rollout with increased timeout
        kubectl rollout status deployment/plantasia --timeout=300s